---
- name: Ensure Docker is installed
  shell: curl -fsSL https://test.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Python docker libraries is installed
  pip:
    name: [docker, docker-compose]
    state: present
