---
- name: Ensure docker-compose.yaml is present
  copy:
    src: docker-compose.yaml
    dest: docker/containers/pihole/

- name: Run pihole container
  docker_compose:
    project_src: docker/containers/pihole
    state: present
