---
- name: Create docker compose project directory
  file:
    path: docker/containers/pihole
    state: directory

- name: Ensure docker-compose.yaml and docker-compose.override.yaml is present
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: docker-compose.yaml.j2
      dest: docker/containers/pihole/docker-compose.yaml
    - src: docker-compose.override.yaml.j2
      dest: docker/containers/pihole/docker-compose.override.yaml

- name: Run pihole container
  docker_compose:
    project_src: docker/containers/pihole
    state: present
